### ISSUE TITLE
the new recommendation flow

### ISSUE THREAD

**Issue by 0marSalah** [Cooperation-org/vc-storage#27]
here is the link to [the architecture](https://drive.google.com/file/d/1grSs-uQchl_XBxT4vWdKWqqDTKc9e1GP/view?usp=sharing)

**Comment by 0marSalah** [comment]
@gvelez17 
so the issue here is we dont wanna others to write anything to my drive but i am giving him the permission to only one file which is RELATIONS file, we can send an email with the new recommendation id and let requester update his file (i think its very clever i like it) but this will require another page to let the requester actually update the RELATIONS file

**Comment by gvelez17** [comment]
My thought is that the best flow is

-------------------------------------------------

  Requestor creates credential on their storage, sends email message with read-only link to recommender
  
  Recommender creates recommendation on thei storage, sends email message with link back to requestor
  
  Requestor views the recommendation in the app and chooses to save it and attach it to their credential

  ------------------------------------------------

  I think this is an important flow for intention and consent but it requires a new app screen
  
  I think that the requestor should save a copy of the recommendation but by their choice
  
  that may be out of scope of the 1-2 week work.  @AmrNabel @0marSalah @longpd 
  
  note @longpd     i strongly think that the requestor should have a copy of the signed recommendation, tho it should point back to the original.  otherwise there could be times that it becomes inaccessible to the requestor. 
  
  In a future version (Not this issue, not this 2 weeks), i think the address of the claim shoudl be inside it, and maybe in the form of a DID that can be resolved.

**Comment by gvelez17** [comment]
> @gvelez17 so the issue here is we dont wanna others to write anything to my drive but i am giving him the permission to only one file which is RELATIONS file, we can send an email with the new recommendation id and let requester update his file (i think its very clever i like it) but this will require another page to let the requester actually update the RELATIONS file

yes this is why pinged @AmrNabel @dev-mhany  we need a page for it.  its ok for now however you do it within the time frame, the main thing is to finish all the items from Phil within this week and next.

**Comment by 0marSalah** [comment]
yeah actually the id of recommendation is a hash version of the requester VC

> My thought is that the best flow is
> 
> Requestor creates credential on their storage, sends email message with read-only link to recommender
> 
> Recommender creates recommendation on thei storage, sends email message with link back to requestor
> 
> Requestor views the recommendation in the app and chooses to save it and attach it to their credential
> 
> I think this is an important flow for intention and consent but it requires a new app screen
> 
> I think that the requestor should save a copy of the recommendation but by their choice
> 
> that may be out of scope of the 1-2 week work. @AmrNabel @0marSalah @longpd
> 
> note @longpd i strongly think that the requestor should have a copy of the signed recommendation, tho it should point back to the original. otherwise there could be times that it becomes inaccessible to the requestor.
> 
> In a future version (Not this issue, not this 2 weeks), i think the address of the claim shoudl be inside it, and maybe in the form of a DID that can be resolved.

**Comment by AmrNabel** [comment]
But in this case if the user has many recommendations and missed some of
them to save on the credential of he not opening his mail it also may be
missed

**Comment by 0marSalah** [comment]
yeah and that will be as rejection for the recommendation!

**Comment by gvelez17** [comment]
yeah ideally we would track them like linkedin and have persistent notification til he actively rejects, but since we don't have state its harder - we could track that he has requested them, but  only with recommender actively hitting his drive we could know for sure its ready

**Comment by AmrNabel** [comment]
In my thoughts is that this app should show all the recommendations, negative and positive ones, So in this flow if the user sees this recommendation not good or he didn't like it he can reject the recommendation, and I think we don't want that

**Comment by AmrNabel** [comment]
My thought is that the app should show all the recommendations, the
negative and positive ones, So if the user sees on the mail that this
recommendation is not good so he can reject it, and I don't think that we
want

**Comment by longpd** [comment]
If this discussion is relevant to the OpenCreds with LinkedClaims Skills authoring tool we're working on with T3 grant support, can we move it to the https://github.com/Cooperation-org/linked-claims-author/issues)Github instance? 

Thankis
